name: my-pyjs-env 
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - pyjs
  - httpx
  - jupyverse-api >=0.9.0
  - fps-frontend
  - fps-lab
  - fps-jupyterlab
  - fps-noauth
  - fps-contents
